### ISSUE TITLE
error: patch failed

### ISSUE THREAD

**Issue by EzzalddeenAli** [jnm/kobo-no-docker#1]
error: patch failed: dependencies/pip/dev_requirements.txt:289
error: dependencies/pip/dev_requirements.txt: patch does not apply
error: patch failed: kobo/settings/base.py:322
error: kobo/settings/base.py: patch does not apply
error: patch failed: package.json:103

**Comment by jnm** [comment]
This should be fixed by #2, but it will almost certainly have to be fixed again :dragon_face:

It's cool that you're using this repo, but beware that it's not officially supported or anything!

If patching fails in the future, I'd suggest looking at the patch and trying manually to do what it does. Currently, that's:
* (in kpi and kobocat) switching from `psycopg2` to `psycopg2-binary` to speed up installation;
* (in kpi) ameding the `copy-fonts` command in `package.json` to call `python3` instead of `python`;
* (in kobocat) trashing a seemingly-unused `savreaderwriter` dependency (see https://github.com/kobotoolbox/kobocat/pull/826), again, to speed up installation
* (in kobocat) removing the `.geturl()` from
  ```
  KOBOFORM_INTERNAL_URL = env.url('KOBOFORM_INTERNAL_URL', KOBOFORM_URL).geturl()
  ```
  …to work around an issue with django-environ (this might not be necessary anymore).

Hopefully, the patches will be smaller—or eliminated completely—in the near future.
